load("//aoc:rules.bzl", "cc_aoc")

cc_aoc(
    name = "day2",
    srcs = [
        "main.c",
    ],
    deps = [
        "//common:utils",
    ],
    input_file = "input.txt",
    example_file = "example.txt",
)
